### ISSUE TITLE
Piper exceptions after upgrade to 2.2.1

### ISSUE THREAD

**Issue by Bikonja** [home-assistant/addons#4384]
### Describe the issue you are experiencing

Yesterday I updated Piper from 2.1.1 to 2.2.1 and it stopped working. Did a restart and tried two TTS commands, here's the logs:

```
[06:11:23] INFO: Successfully send discovery information to Home Assistant.
s6-rc: info: service discovery successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='wyoming event handler' coro=<AsyncEventHandler.run() done, defined at /usr/local/lib/python3.11/dist-packages/wyoming/server.py:31> exception=Error('# channels not specified')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 234, in _handle_synthesize
    _VOICE.synthesize_wav(text, wav_writer, syn_config)
  File "/usr/local/lib/python3.11/dist-packages/piper/voice.py", line 401, in synthesize_wav
    for audio_chunk in self.synthesize(
  File "/usr/local/lib/python3.11/dist-packages/piper/voice.py", line 285, in synthesize
    sentence_phonemes = self.phonemize(text)
                        ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/piper/voice.py", line 233, in phonemize
    _ESPEAK_PHONEMIZER = EspeakPhonemizer(self.espeak_data_dir)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/piper/phonemize_espeak.py", line 17, in __init__
    from . import espeakbridge  # avoid circular import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'espeakbridge' from 'piper' (/usr/local/lib/python3.11/dist-packages/piper/__init__.py)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wyoming/server.py", line 41, in run
    if not (await self.handle_event(event)):
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 137, in handle_event
    raise err
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 111, in handle_event
    await self._handle_synthesize(self._synthesize)
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 233, in _handle_synthesize
    with wav_writer:
  File "/usr/lib/python3.11/wave.py", line 453, in __exit__
    self.close()
  File "/usr/lib/python3.11/wave.py", line 565, in close
    self._ensure_header_written(0)
  File "/usr/lib/python3.11/wave.py", line 583, in _ensure_header_written
    raise Error('# channels not specified')
wave.Error: # channels not specified
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='wyoming event handler' coro=<AsyncEventHandler.run() done, defined at /usr/local/lib/python3.11/dist-packages/wyoming/server.py:31> exception=Error('# channels not specified')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 234, in _handle_synthesize
    _VOICE.synthesize_wav(text, wav_writer, syn_config)
  File "/usr/local/lib/python3.11/dist-packages/piper/voice.py", line 401, in synthesize_wav
    for audio_chunk in self.synthesize(
  File "/usr/local/lib/python3.11/dist-packages/piper/voice.py", line 285, in synthesize
    sentence_phonemes = self.phonemize(text)
                        ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/piper/voice.py", line 233, in phonemize
    _ESPEAK_PHONEMIZER = EspeakPhonemizer(self.espeak_data_dir)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/piper/phonemize_espeak.py", line 17, in __init__
    from . import espeakbridge  # avoid circular import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'espeakbridge' from 'piper' (/usr/local/lib/python3.11/dist-packages/piper/__init__.py)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wyoming/server.py", line 41, in run
    if not (await self.handle_event(event)):
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 137, in handle_event
    raise err
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 120, in handle_event
    await self._handle_synthesize(self._synthesize)
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 233, in _handle_synthesize
    with wav_writer:
  File "/usr/lib/python3.11/wave.py", line 453, in __exit__
    self.close()
  File "/usr/lib/python3.11/wave.py", line 565, in close
    self._ensure_header_written(0)
  File "/usr/lib/python3.11/wave.py", line 583, in _ensure_header_written
    raise Error('# channels not specified')
wave.Error: # channels not specified
```

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which app are you reporting an issue with?

Piper

### What is the version of the app?

2.2.1

### Steps to reproduce the issue

1. Update Piper to 2.2.1
2. Run tts.speak action, e.g.

```
- action: tts.speak
    metadata: {}
    target:
      entity_id: tts.piper
    data:
      cache: false
      media_player_entity_id: media_player.my_player
      message: Test
```

## System Information

version | core-2026.1.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
container_arch | aarch64
user | root
virtualenv | false
python_version | 3.13.11
os_name | Linux
os_version | 6.12.47-haos-raspi
arch | aarch64
timezone | Europe/Dublin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.5
Stage | running
Available Repositories | 2687
Downloaded Repositories | 14

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 17.0
-- | --
update_channel | stable
supervisor_version | supervisor-2026.01.1
agent_version | 1.8.1
docker_version | 29.1.3
disk_total | 110.0 GB
disk_used | 17.1 GB
nameservers | 192.168.88.45
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.5.2), Terminal & SSH (9.22.0), File editor (5.8.0), go2rtc (1.9.14), SQLite Web (5.0.0), InfluxDB (5.0.2), Samba share (12.5.4), Matter Server (8.2.2), Piper (2.2.1), Music Assistant (2.7.6), ESPHome Device Builder (2026.1.3), Everything Presence Zone Configurator (2.0.12)

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 8
views | 18
mode | storage

</details>

<details><summary>Network Configuration</summary>

adapters | lo (disabled), end0 (enabled, default, auto), docker0 (disabled), hassio (disabled), veth24f21ef (disabled), vethc2a2fdd (disabled), vethc038645 (disabled), veth05a0e46 (disabled), veth572b34e (disabled), veth6d0a689 (disabled), veth18ffbd3 (disabled), veth0c5900d (disabled), veth84482c5 (disabled), veth6476e26 (disabled), vethfcc0654 (disabled), veth03a8b4a (disabled)
-- | --
ipv4_addresses | lo (127.0.0.1/8), end0 (192.168.x.y/zz), docker0 (172.30.232.1/23), hassio (172.30.32.1/23), veth24f21ef (), vethc2a2fdd (), vethc038645 (), veth05a0e46 (), veth572b34e (), veth6d0a689 (), veth18ffbd3 (), veth0c5900d (), veth84482c5 (), veth6476e26 (), vethfcc0654 (), veth03a8b4a ()
ipv6_addresses | lo (::1/128), end0 (fe80::fff8:10fb:37c6:xxxx/64), docker0 (fe80::4cd2:84ff:fef4:xxxx/64), hassio (fe80::c06a:fbff:feb6:xxxx64), veth24f21ef (fe80::9cb9:b5ff:fe61:xxxx/64), vethc2a2fdd (fe80::4456:8dff:feb6:xxxx/64), vethc038645 (fe80::446d:fbff:fefc:xxxx/64), veth05a0e46 (fe80::544d:b1ff:fe3c:xxxx/64), veth572b34e (fe80::e885:1dff:feeb:xxxx/64), veth6d0a689 (fe80::24b3:f7ff:xxxx:8f/64), veth18ffbd3 (fe80::23:d0ff:xxxx:550/64), veth0c5900d (fe80::302f:c2ff:fee0:xxxx/64), veth84482c5 (fe80::70be:71ff:fe0d:xxxx/64), veth6476e26 (fe80::7cb9:4dff:fe39:xxxx/64), vethfcc0654 (fe80::642c:17ff:fe6c:xxxx/64), veth03a8b4a (fe80::e803:31ff:feb0:xxxx/64)
announce_addresses | 192.168.x.y, fe80::fff8:10fb:37c6:xxxx

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 24 January 2026 at 19:57
-- | --
current_recorder_run | 1 February 2026 at 19:35
estimated_db_size | 1368.70 MiB
database_engine | sqlite
database_version | 3.49.2

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
Nothing useful
```

### Anything in the app logs that might be useful for us?

```txt
[06:11:23] INFO: Successfully send discovery information to Home Assistant.
s6-rc: info: service discovery successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='wyoming event handler' coro=<AsyncEventHandler.run() done, defined at /usr/local/lib/python3.11/dist-packages/wyoming/server.py:31> exception=Error('# channels not specified')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 234, in _handle_synthesize
    _VOICE.synthesize_wav(text, wav_writer, syn_config)
  File "/usr/local/lib/python3.11/dist-packages/piper/voice.py", line 401, in synthesize_wav
    for audio_chunk in self.synthesize(
  File "/usr/local/lib/python3.11/dist-packages/piper/voice.py", line 285, in synthesize
    sentence_phonemes = self.phonemize(text)
                        ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/piper/voice.py", line 233, in phonemize
    _ESPEAK_PHONEMIZER = EspeakPhonemizer(self.espeak_data_dir)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/piper/phonemize_espeak.py", line 17, in __init__
    from . import espeakbridge  # avoid circular import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'espeakbridge' from 'piper' (/usr/local/lib/python3.11/dist-packages/piper/__init__.py)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wyoming/server.py", line 41, in run
    if not (await self.handle_event(event)):
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 137, in handle_event
    raise err
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 111, in handle_event
    await self._handle_synthesize(self._synthesize)
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 233, in _handle_synthesize
    with wav_writer:
  File "/usr/lib/python3.11/wave.py", line 453, in __exit__
    self.close()
  File "/usr/lib/python3.11/wave.py", line 565, in close
    self._ensure_header_written(0)
  File "/usr/lib/python3.11/wave.py", line 583, in _ensure_header_written
    raise Error('# channels not specified')
wave.Error: # channels not specified
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='wyoming event handler' coro=<AsyncEventHandler.run() done, defined at /usr/local/lib/python3.11/dist-packages/wyoming/server.py:31> exception=Error('# channels not specified')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 234, in _handle_synthesize
    _VOICE.synthesize_wav(text, wav_writer, syn_config)
  File "/usr/local/lib/python3.11/dist-packages/piper/voice.py", line 401, in synthesize_wav
    for audio_chunk in self.synthesize(
  File "/usr/local/lib/python3.11/dist-packages/piper/voice.py", line 285, in synthesize
    sentence_phonemes = self.phonemize(text)
                        ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/piper/voice.py", line 233, in phonemize
    _ESPEAK_PHONEMIZER = EspeakPhonemizer(self.espeak_data_dir)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/piper/phonemize_espeak.py", line 17, in __init__
    from . import espeakbridge  # avoid circular import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'espeakbridge' from 'piper' (/usr/local/lib/python3.11/dist-packages/piper/__init__.py)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wyoming/server.py", line 41, in run
    if not (await self.handle_event(event)):
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 137, in handle_event
    raise err
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 120, in handle_event
    await self._handle_synthesize(self._synthesize)
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 233, in _handle_synthesize
    with wav_writer:
  File "/usr/lib/python3.11/wave.py", line 453, in __exit__
    self.close()
  File "/usr/lib/python3.11/wave.py", line 565, in close
    self._ensure_header_written(0)
  File "/usr/lib/python3.11/wave.py", line 583, in _ensure_header_written
    raise Error('# channels not specified')
wave.Error: # channels not specified
```

**Comment by Geoff-Public** [comment]
I can confirm this regression on Piper add-on 2.2.1.

After updating from 2.1.1 to 2.2.1, all Piper TTS requests fail with:

     **ImportError: cannot import name 'espeakbridge' from 'piper'
    wave.Error: # channels not specified**

This results in zero audio being produced, and Home Assistant logs ffmpeg pipe:0 errors.

Rolling back the add-on via a pre-update backup to Piper **2.1.1** restores full functionality.

Home Assistant version: 2026.1.3
Supervisor version: 2026.01.1
Hardware/architecture: Raspberry Pi

**Comment by RMMTSLLP** [comment]
After ugrade to 2.2.1 no speech is output even tested using developer tools  action tts-speak, piper action runs as normal showing action completed, no output is heard reverted back to 2.1.1 function works again

**Comment by ablohm** [comment]
Same here. Since this was my first install I was really puzzled what I did wrong.

**Comment by Jacythesailor** [comment]
Yeah same here. What did you guys do?

**Comment by phill123** [comment]
> Same here. Since this was my first install I was really puzzled what I did wrong.

I buy an atom echo, install it pulling my hair out over why it wont talk back or generate the test voices and i see this post. Man we just picked a bad time... Wish we could rollback however this is the first install so no backup to roll back on.... Atleast the STT works and i can carry out commands.....

**Comment by Jacythesailor** [comment]
Yeah I spent a solid 3 weeks custom-building an AI server and running it through a Raspberry Pi to finally get my home all setup then when I am just about done, I see an update and get excited for a new feture only for it to break my whole system.   :(

**Comment by Dschoni** [comment]
Same issue - is there a way to install Piper 2.1.1 as a new user?
This is my first try, so there's no backup of an older version.

**Comment by Vcenzo** [comment]
Same issue, version 2.2.1 it's broken on Raspberry Pi

**Comment by mklimasz5** [comment]
Reporting similar behavior:

After successfully running on Wyoming-Piper 2.1.1 (if I'm not mistaken) upon upgrade to 2.2.1 all my ESP32 satellites (based on ESP32-S3-WROOM-1 modules) immediately lost possibility to announce anything. They're able to play music (via Media menu), but that's it. It seem that the content is reported to be generated (apparently with correct network address and URL link where satellite would fetch the wav file for media player to announce), but downloading is stuck.

Attaching log from satellite - **all runs smooth only until the final announcement**:

[13:45:17.968][D][micro_wake_word:325]: Detected 'Hey Mycroft' with sliding average probability is 1.00 and max probability is 1.00
[13:45:17.968][D][voice_assistant:482]: State changed from IDLE to START_MICROPHONE
[13:45:17.968][D][voice_assistant:489]: Desired state set to START_PIPELINE
[13:45:17.984][D][micro_wake_word:370]: Stopping wake word detection
[13:45:17.984][D][voice_assistant:208]: Starting Microphone
[13:45:17.984][D][ring_buffer:034]: Created ring buffer with size 16384
[13:45:17.984][D][voice_assistant:482]: State changed from START_MICROPHONE to STARTING_MICROPHONE
[13:45:17.984][D][micro_wake_word:378]: State changed from DETECTING_WAKE_WORD to STOPPING
[13:45:17.984][D][voice_assistant:482]: State changed from STARTING_MICROPHONE to START_PIPELINE
[13:45:18.015][D][micro_wake_word:274]: Inference task is stopping, deallocating buffers
[13:45:18.015][D][micro_wake_word:279]: Inference task is finished, freeing task resources
[13:45:18.015][D][micro_wake_word:378]: State changed from STOPPING to STOPPED
[13:45:18.031][D][voice_assistant:229]: Requesting start
[13:45:18.031][D][voice_assistant:482]: State changed from START_PIPELINE to STARTING_PIPELINE
[13:45:18.031][D][voice_assistant:504]: Client started, streaming microphone
[13:45:18.046][D][voice_assistant:482]: State changed from STARTING_PIPELINE to STREAMING_MICROPHONE
[13:45:18.046][D][voice_assistant:489]: Desired state set to STREAMING_MICROPHONE
[13:45:18.046][D][voice_assistant:628]: Event Type: 1
[13:45:18.046][D][voice_assistant:631]: Assist Pipeline running
[13:45:18.046][D][voice_assistant:628]: Event Type: 3
[13:45:18.046][D][voice_assistant:650]: STT started
[13:45:18.062][D][light:091]: 'ESP32-voice2' Setting:
[13:45:18.062][D][light:115]:   Red: 0%, Green: 0%, Blue: 100%
[13:45:18.062][D][light:165]:   Effect: 'Slow Pulse'
[13:45:20.077][D][voice_assistant:628]: Event Type: 11
[13:45:20.124][D][voice_assistant:831]: Starting STT by VAD
[13:45:22.186][D][voice_assistant:628]: Event Type: 12
[13:45:22.186][D][voice_assistant:835]: STT by VAD end
[13:45:22.186][D][voice_assistant:482]: State changed from STREAMING_MICROPHONE to STOP_MICROPHONE
[13:45:22.202][D][voice_assistant:489]: Desired state set to AWAITING_RESPONSE
[13:45:22.202][D][light:091]: 'ESP32-voice2' Setting:
[13:45:22.202][D][light:115]:   Red: 0%, Green: 0%, Blue: 100%
[13:45:22.202][D][light:165]:   Effect: 'Fast Pulse'
[13:45:22.217][D][voice_assistant:482]: State changed from STOP_MICROPHONE to STOPPING_MICROPHONE
[13:45:22.217][D][voice_assistant:482]: State changed from STOPPING_MICROPHONE to AWAITING_RESPONSE
[13:45:23.264][D][voice_assistant:628]: Event Type: 4
[13:45:23.279][D][voice_assistant:667]: Speech recognised as: "what is the weather"
[13:45:23.279][D][voice_assistant:628]: Event Type: 5
[13:45:23.279][D][voice_assistant:672]: Intent started
[13:45:23.279][D][voice_assistant:628]: Event Type: 6
[13:45:23.279][D][voice_assistant:628]: Event Type: 7
[13:45:23.279][D][voice_assistant:725]: Response: "1.8 °C and cloudy"
[13:45:23.295][D][voice_assistant:628]: Event Type: 8
[13:45:23.295][D][voice_assistant:747]: Response URL: "http://192.168.1.180:8123/api/tts_proxy/4vHKF945OjpASR4PUD5yHw.wav"
[13:45:23.295][D][voice_assistant:482]: State changed from AWAITING_RESPONSE to STREAMING_RESPONSE
[13:45:23.295][D][voice_assistant:489]: Desired state set to STREAMING_RESPONSE
[13:45:23.295][D][light:091]: 'ESP32-voice2' Setting:
[13:45:23.295][D][light:079]:   Brightness: 50%
[13:45:23.295][D][light:115]:   Red: 0%, Green: 0%, Blue: 100%
[13:45:23.295][D][light:165]:   Effect: 'None'
[13:45:23.295][D][media_player:084]: 'ESP32-voice2' - Setting
[13:45:23.295][D][media_player:091]:   Media URL: http://192.168.1.180:8123/api/tts_proxy/4vHKF945OjpASR4PUD5yHw.wav
[13:45:23.295][D][media_player:097]:  Announcement: yes
[13:45:23.311][D][light:091]: 'ESP32-voice2' Setting:
[13:45:23.311][D][light:079]:   Brightness: 50%
[13:45:23.311][D][light:115]:   Red: 0%, Green: 0%, Blue: 100%
[13:45:23.311][D][speaker_media_player:410]: State changed to ANNOUNCING
[13:45:23.326][D][voice_assistant:628]: Event Type: 2
[13:45:23.326][D][voice_assistant:770]: Assist Pipeline ended
**[13:45:58.914][E][speaker_media_player.pipeline:112]: Media reader encountered an error: ESP_FAIL
[13:45:58.914][E][speaker_media_player:330]: The announcement pipeline's file reader encountered an error.
[13:45:58.914][E][audio_reader:142][ann_read]: Failed to fetch headers**

At the same time, playback of the media works just fine:
[14:12:51.553][D][media_player:084]: 'ESP32-voice2' - Setting
[14:12:51.555][D][media_player:091]:   Media URL: http://192.168.1.180:8123/api/esphome/ffmpeg_proxy/96ffe8b368e81b2860a0ebd4d9de22bc/wrCBvtoDZAylD3Pqs3K6kQ.wav
[14:12:51.555][D][micro_wake_word:370]: Stopping wake word detection
[14:12:51.571][D][light:091]: 'ESP32-voice2' Setting:
[14:12:51.572][D][light:079]:   Brightness: 50%
[14:12:51.572][D][light:115]:   Red: 0%, Green: 0%, Blue: 100%
[14:12:51.588][D][light:165]:   Effect: 'None'
[14:12:51.589][D][speaker_media_player:410]: State changed to ANNOUNCING
[14:12:51.589][D][micro_wake_word:378]: State changed from DETECTING_WAKE_WORD to STOPPING
[14:12:51.589][D][micro_wake_word:274]: Inference task is stopping, deallocating buffers
[14:12:51.605][D][micro_wake_word:279]: Inference task is finished, freeing task resources
[14:12:51.605][D][micro_wake_word:378]: State changed from STOPPING to STOPPED
[14:12:51.624][D][speaker_media_player.pipeline:114]: Reading WAV file type
[14:12:51.672][D][ring_buffer:034][ann_read]: Created ring buffer with size 8192
[14:12:51.905][D][speaker_media_player.pipeline:124]: Decoded audio has 2 channels, 48000 Hz sample rate, and 16 bits per sample
[14:12:51.927][D][i2s_audio.speaker:102]: Starting
[14:12:51.927][D][i2s_audio.speaker:106]: Started
[14:12:51.927][D][ring_buffer:034][speaker_task]: Created ring buffer with size 19200
[14:12:58.755][D][media_player:084]: 'ESP32-voice2' - Setting
[14:12:58.820][D][media_player:088]:   Command: STOP
[14:12:58.821][D][i2s_audio.speaker:111]: Stopping
[14:12:58.830][D][i2s_audio.speaker:116]: Stopped
[14:12:58.830][D][micro_wake_word:360]: Starting wake word detection
[14:12:58.830][D][light:091]: 'ESP32-voice2' Setting:
[14:12:58.833][D][light:079]:   Brightness: 10%
[14:12:58.836][D][light:115]:   Red: 20%, Green: 100%, Blue: 20%
[14:12:58.836][D][light:165]:   Effect: 'Chill Pulse'
[14:12:58.840][D][speaker_media_player:410]: State changed to IDLE
[14:12:58.853][D][micro_wake_word:378]: State changed from STOPPED to STARTING
[14:12:58.853][D][micro_wake_word:262]: Inference task has started, attempting to allocate memory for buffers
[14:12:58.869][D][micro_wake_word:267]: Inference task is running
[14:12:58.885][D][micro_wake_word:378]: State changed from STARTING to DETECTING_WAKE_WORD
[14:12:58.885][D][ring_buffer:034][mww]: Created ring buffer with size 3840

If, however, I'd try to play announcement (through Media menu, just forcing TTS engine to say anything through satellite), it fails:
[14:16:14.499][D][media_player:084]: 'ESP32-voice2' - Setting
[14:16:14.515][D][media_player:091]:   Media URL: http://192.168.1.180:8123/api/esphome/ffmpeg_proxy/96ffe8b368e81b2860a0ebd4d9de22bc/vSILzgY-fikdWzI6iOPR8Q.wav
[14:16:14.515][D][media_player:097]:  Announcement: yes
[14:16:14.515][D][micro_wake_word:370]: Stopping wake word detection
[14:16:14.515][D][light:091]: 'ESP32-voice2' Setting:
[14:16:14.515][D][light:079]:   Brightness: 50%
[14:16:14.532][D][light:115]:   Red: 0%, Green: 0%, Blue: 100%
[14:16:14.532][D][light:165]:   Effect: 'None'
[14:16:14.532][D][speaker_media_player:410]: State changed to ANNOUNCING
[14:16:14.549][D][micro_wake_word:378]: State changed from DETECTING_WAKE_WORD to STOPPING
[14:16:14.549][D][micro_wake_word:274]: Inference task is stopping, deallocating buffers
[14:16:14.549][D][micro_wake_word:279]: Inference task is finished, freeing task resources
[14:16:14.565][D][micro_wake_word:378]: State changed from STOPPING to STOPPED
[14:16:14.582][D][speaker_media_player.pipeline:114]: Reading WAV file type
[14:16:14.582][D][ring_buffer:034][ann_read]: Created ring buffer with size 8192
[14:16:24.241][D][wifi:2112]: Roam scan (-68 dBm, attempt 1/3)
**[14:16:44.682][E][speaker_media_player:330]: The announcement pipeline's file reader encountered an error.
[14:16:44.682][E][audio_reader:305][ann_read]: Timed out**
[14:16:44.729][D][speaker_media_player.pipeline:114]: Reading WAV file type
[14:16:44.776][D][ring_buffer:034][ann_read]: Created ring buffer with size 8192
[14:16:48.193][D][media_player:084]: 'ESP32-voice2' - Setting
[14:16:48.293][D][media_player:088]:   Command: STOP
[14:16:49.758][D][micro_wake_word:360]: Starting wake word detection
[14:16:49.773][D][light:091]: 'ESP32-voice2' Setting:
[14:16:49.773][D][light:079]:   Brightness: 10%
[14:16:49.773][D][light:115]:   Red: 20%, Green: 100%, Blue: 20%
[14:16:49.773][D][light:165]:   Effect: 'Chill Pulse'
[14:16:49.789][D][speaker_media_player:410]: State changed to IDLE
[14:16:49.789][D][media_player:084]: 'ESP32-voice2' - Setting
[14:16:49.789][D][media_player:088]:   Command: STOP
[14:16:49.789][D][micro_wake_word:378]: State changed from STOPPED to STARTING
[14:16:49.821][D][micro_wake_word:262]: Inference task has started, attempting to allocate memory for buffers
[14:16:49.821][D][micro_wake_word:267]: Inference task is running
[14:16:49.821][D][micro_wake_word:378]: State changed from STARTING to DETECTING_WAKE_WORD
[14:16:49.836][D][ring_buffer:034][mww]: Created ring buffer with size 3840

**Comment by Bikonja** [comment]
Can confirm 2.2.2 fixes the issue
