### ISSUE TITLE
Piper TTS / Wyoming not working: starts up but crashes on every use

### ISSUE THREAD

**Issue by rixx** [home-assistant/addons#4419]
### Describe the issue you are experiencing

I installed the Piper integration (`core_piper`) as directed by the documentation, it is running as v1.6.0. I added the Wyoming Integration via the auto-discovery, which showed up as soon as the Piper integration was installed. The app starts up cleanly, but does not produce sound when called via a script, instead showing a traceback every time.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which app are you reporting an issue with?

Piper

### What is the version of the app?

1.6.0

### Steps to reproduce the issue

Run the following script:

```
sequence:
  - action: tts.speak
    metadata: {}
    target:
      entity_id: tts.piper
    data:
      cache: false
      media_player_entity_id: media_player.unnamed_room_2
      message: test
alias: tts-test
description: ""
```

Notably the same script with ``entity_id: tts.google_en_com`` works fine.

## System Information

version | core-2026.2.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
container_arch | aarch64
user | root
virtualenv | false
python_version | 3.13.11
os_name | Linux
os_version | 6.12.47-haos-raspi
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4994
Installed Version | 2.0.5
Stage | running
Available Repositories | 2711
Downloaded Repositories | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 17.1
-- | --
update_channel | stable
supervisor_version | supervisor-2026.02.1
agent_version | 1.8.1
docker_version | 29.1.3
disk_total | 113.6 GB
disk_used | 14.8 GB
nameservers | 2a02:8071:a86:1f20:b6fc:7dff:fe6f:24a7, fdfe:b0aa:7509:0:b6fc:7dff:fe6f:24a7, 192.168.4.1
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | ESPHome Device Builder (2025.6.2), Tailscale (0.25.0), File editor (5.8.0), Get HACS (1.3.1), Advanced SSH & Web Terminal (21.0.0), Calibre (8.5.0), Calibre-web (0.6.24), Piper (1.6.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 4
views | 5
mode | storage

</details>

<details><summary>Network Configuration</summary>

adapters | lo (disabled), end0 (enabled, default, auto), docker0 (disabled), hassio (disabled), veth0d1d55a (disabled), veth1e46349 (disabled), vethdcdbad8 (disabled), vethf7c184b (disabled), veth622671e (disabled), veth4cdd337 (disabled), veth2c32dc9 (disabled), veth335b5e0 (disabled), vetha61865e (disabled)
-- | --
ipv4_addresses | lo (127.0.0.1/8), end0 (192.168.4.28/24), docker0 (172.30.232.1/23), hassio (172.30.32.1/23), veth0d1d55a (), veth1e46349 (), vethdcdbad8 (), vethf7c184b (), veth622671e (), veth4cdd337 (), veth2c32dc9 (), veth335b5e0 (), vetha61865e ()
ipv6_addresses | lo (::1/128), end0 (2a02:8071:a86:1f20:9d0a:b1e5:8450:e0e4/64, fdfe:b0aa:7509:0:2b36:1e0:7e15:7218/64, fe80::6cdb:6982:9e3c:19fb/64), docker0 (fe80::5c46:79ff:fe2f:4b21/64), hassio (fe80::107d:2bff:fec7:b701/64), veth0d1d55a (fe80::dc7f:9bff:fe0f:7cc2/64), veth1e46349 (fe80::442:1aff:feac:8e45/64), vethdcdbad8 (fe80::1401:a1ff:fe5f:a2b9/64), vethf7c184b (fe80::1803:8bff:fe36:85e8/64), veth622671e (fe80::b8a8:f1ff:fea4:1332/64), veth4cdd337 (fe80::1c34:24ff:feaa:1219/64), veth2c32dc9 (fe80::ccfd:f3ff:feb3:7017/64), veth335b5e0 (fe80::e0d4:1ff:fe47:65ff/64), vetha61865e (fe80::a8c0:b4ff:fe49:ed87/64)
announce_addresses | 192.168.4.28, 2a02:8071:a86:1f20:9d0a:b1e5:8450:e0e4, fdfe:b0aa:7509:0:2b36:1e0:7e15:7218, fe80::6cdb:6982:9e3c:19fb

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 27 July 2025 at 08:28
-- | --
current_recorder_run | 13 February 2026 at 07:54
estimated_db_size | 321.93 MiB
database_engine | sqlite
database_version | 3.49.2

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
-
```

### Anything in the app logs that might be useful for us?

```txt
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='wyoming event handler' coro=<AsyncEventHandler.run() done, defined at /usr/local/lib/python3.11/dist-packages/wyoming/server.py:31> exception=AttributeError("'NoneType' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wyoming/server.py", line 41, in run
    if not (await self.handle_event(event)):
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 111, in handle_event
    raise err
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 72, in handle_event
    stream_start = SynthesizeStart.from_event(event)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wyoming/tts.py", line 121, in from_event
    context=event.data.get("context"),
            ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='wyoming event handler' coro=<AsyncEventHandler.run() done, defined at /usr/local/lib/python3.11/dist-packages/wyoming/server.py:31> exception=AttributeError("'NoneType' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wyoming/server.py", line 41, in run
    if not (await self.handle_event(event)):
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 111, in handle_event
    raise err
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 72, in handle_event
    stream_start = SynthesizeStart.from_event(event)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wyoming/tts.py", line 121, in from_event
    context=event.data.get("context"),
            ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by rixx** [comment]
Looking around, I see now that 1.6.0 is terribly out of date. I have no idea why this version would install – I have never used Piper before and installed it today on an up-to-date HAOS/HA instance. Why would an up-to-date HA install a super old add-on version? 

Working with the current 2.2.x though!
